all: run less

run:
	perl fix-yahoo.pl out.csv data-in/gdp.csv data-in/manufacture-orders.csv data-in/manufacture-durable.csv break data-in/spy.csv data-in/gld.csv data-in/slv.csv

less:
	less out.csv
